# generated by https://scriptim.github.io/bash-prompt-generator/
PS1='\t \[\e[38;5;208m\]\u\[\e[38;5;40m\]@\[\e[0m\]\h\[\e[38;5;40m\]>\[\e[38;5;33m\]\w\[\e[0m\]\\$ \[\e[38;5;40m\]$(git branch 2>/dev/null | grep '"'"' ^* '"'"' | colrm 1 2) \[\e[0m\]'
