# generated by https://scriptim.github.io/bash-prompt-generator/
PS1='\[\e[0m\]\t \[\e[0;38;5;208m\]\u\[\e[0;38;5;84m\]@\[\e[0m\]\h\[\e[0;38;5;84m\]>\[\e[0;38;5;32m\]\w\[\e[0m\]$ \[\e[0;7;38;5;202m\]$(git branch 2>/dev/null | grep '"'"'^*'"'"' | colrm 1 2)\[\e[0m\]'
test lkr
